services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pgvector-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vectordb
    ports:
      - "5433:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
    external: true
    name: 8a20fe419f9cb5056efc5b404d874108b1427012abea8bac2313d6d0b3c17ea1
